Repository etiennecallies/click-and-collect, pull requests merged in 2021-05, with the labels that each got.

#78 Commute exchange rules
  focused_proof.ml
  proof.ml
Labels: enhancement

#81 Help auto-prover
  static/index.html
Labels: documentation

#72 Auto-weakening mode for 1 rule and axiom rule
  apply_rule.ml
  click_and_collect.eliom
  proof.ml
  static/css/style.css
  static/js/app.js
  static/js/proof.js
  test/api_test.ml
  test/api_test_data.json
Labels: feature, help wanted

#85 Timeout for auto prover
  focused_proof.ml
  static/css/style.css
  static/js/sequent.js
  test/api_test_data.json
Labels: enhancement

#86 Help autoweak in info popup
  static/css/images/ui-icons_444444_256x240.png
  static/css/images/ui-icons_555555_256x240.png
  static/css/images/ui-icons_777620_256x240.png
  static/css/images/ui-icons_777777_256x240.png
  static/css/images/ui-icons_cc0000_256x240.png
  static/css/images/ui-icons_ffffff_256x240.png
  static/css/style.css
  static/index.html
  static/js/app.js
  static/js/proof.js
Labels: documentation

#88 Correct axiom detection for auto-weak
  proof.ml
  test/api_test.ml
  test/api_test_data.json
Labels: bug

#91 Fixed bound to 4.
  focused_proof.ml
  test/api_test_data.json
Labels: bug

#92 Links to wiki
  README.md
  static/index.html
Labels: documentation

#93 commute weakenings downwards
  click_and_collect.eliom
  focused_proof.ml
  proof.ml
  test/api_test.ml
  test/api_test_data.json
Labels: enhancement

#96 [auto-reverse] remove dereliction on ??-formulas
  proof.ml
  sequent.ml
  static/index.html
Labels: bug

#99 Implicit exchange
  click_and_collect.eliom
  export_as_latex.ml
  focused_proof.ml
  proof.ml
  rule_request.ml
  static/js/proof.js
  static/js/sequent.js
Labels: feature

#101 Update implicit/explicit export comments
  static/index.html
Labels: documentation

#102 Simple code cleaning and small bug correction
  export_as_latex.ml
  focused_proof.ml
  nanoyalla/macroll.v
  proof.ml
  sequent.ml
Labels: bug, code improvement

#98 [Coq] utf8 notations in Coq export
  export_as_coq.ml
  nanoyalla/README.md
  nanoyalla/macroll.v
  proof.ml
  static/download/nanoyalla.zip
Labels: enhancement

#100 Proof marshaling
  Makefile.options
  README.md
  click_and_collect.eliom
  export_as_coq.ml
  export_as_latex.ml
  proof.ml
  proof_compression.ml
  proof_marshal.ml
  static/css/style.css
  static/images/share-icon.png
  static/js/app.js
  static/js/proof.js
  static/js/sequent.js
  test/api_test.ml
Labels: feature

#107 [Proof save] add documentation on main page
  static/index.html
Labels: documentation

#103 [export] add ascii and utf8
  export_as_latex.ml
  proof.ml
  sequent.ml
  static/css/style.css
  static/images/LaTeX_logo.png
  static/images/pdf-icon.png
  static/index.html
  static/js/app.js
  static/js/proof.js
Labels: code improvement, feature

#112 [export] correct parentheses for unary symbols
  sequent.ml
Labels: regression

#108 Add cut front and back
  README.md
  click_and_collect.eliom
  export_as_coq.ml
  nanoyalla/README.md
  nanoyalla/macroll.v
  parse_sequent.ml
  proof.ml
  raw_sequent.ml
  rule_request.ml
  static/css/style.css
  static/download/nanoyalla.zip
  static/index.html
  static/js/app.js
  static/js/proof.js
  static/js/sequent.js
Labels: feature

#110 Remove loop up to exchange and up to weakening
  focused_proof.ml
  proof.ml
  sequent.ml
  test/api_test_data.json
Labels: enhancement

#120 [Coq] Simplified axiom expansion tactic
  export_as_coq.ml
  nanoyalla/README.md
  nanoyalla/macroll.v
  static/download/nanoyalla.zip
  test/coq_test_data/axexpansion.v
  test/coq_test_data/example1.v
  test/coq_test_data/example2.v
  test/coq_test_data/example3.v
Labels: code improvement
