Repository etiennecallies/click-and-collect, pull requests merged in 2021-04, with the labels that each got.

#34 rename coq export file
  static/js/proof.js
  test/coq_test.sh
Labels: code improvement

#37 Select only some examples for tutorial
  static/index.html
Labels: documentation

#32 Remove context notation from main page
  static/index.html
Labels: documentation

#35 Better Coq export
  export_as_coq.ml
  proof.ml
  sequent.ml
Labels: enhancement, feature

#40 [NanoYalla] Tactic for generalized use of axioms
  export_as_coq.ml
  nanoyalla/README.md
  nanoyalla/macroll.v
  proof.ml
  static/download/nanoyalla.zip
  test/coq_test_data/example1.v
  test/coq_test_data/example2.v
  test/coq_test_data/example3.v
Labels: bug

#41 [Test] add json test files
  test/proof_test_data/ax.json
  test/proof_test_data/lcm23.json
  test/proof_test_data/list.json
  test/proof_test_data/schellinx.json
  test/proof_test_data/wu.json
Labels: code improvement

#33 LaTeX export
  .gitignore
  click_and_collect.eliom
  export_as_latex.ml
  latex/example.tex
  proof.ml
  sequent.ml
Labels: feature

#46 update README.md to test infrastructure
  README.md
Labels: documentation

#53 Update index.html: more structure in main page
  static/css/style.css
  static/index.html
Labels: documentation

#54 Check provability
  clauses.ml
  click_and_collect.eliom
  is_sequent_provable.ml
  phase.ml
  sequent.ml
  static/css/style.css
  static/images/pdf-icon.png
  static/index.html
  static/js/app.js
  static/js/proof.js
  test/api_test.ml
  test/api_test_data.json
Labels: feature

#56 [nanoyalla] minor code modifications
  nanoyalla/README.md
  nanoyalla/macroll.v
  nanoyalla/nanoll.v
  static/download/nanoyalla.zip
Labels: code improvement

#57 [latex] shorter header comments
  export_as_latex.ml
Labels: documentation

#62 [LaTeX] new export: better for large proofs
  export_as_latex.ml
Labels: enhancement

#58 Auto reverse
  apply_rule.ml
  click_and_collect.eliom
  export_as_coq.ml
  export_as_latex.ml
  is_proof_complete.ml
  proof.ml
  sequent.ml
  static/css/style.css
  static/images/coq.png
  static/js/app.js
  static/js/proof.js
  test/api_test.ml
  test/api_test_data.json
Labels: feature

#51 Towards auto-reverse
  reverse.ml
Labels: feature

#55 More phase non-provability checks
  phase.ml
  test/api_test_data.json
Labels: enhancement

#70 Provability check through balanced additive slices
  is_sequent_provable.ml
  slice.ml
  test/api_test_data.json
Labels: enhancement

#77 Refacto focus proof
  focused_proof.ml
Labels: code improvement
