Repository etiennecallies/click-and-collect, pull requests merged in 2021-06, with the labels that each got.

#123 [Readme] Add missing url
  README.md
Labels: documentation

#124 [Coq] Simplified scope notation
  export_as_coq.ml
  nanoyalla/README.md
  nanoyalla/macroll.v
  proof.ml
  static/download/nanoyalla.zip
Labels: code improvement

#122 Introduce notations
  apply_rule.ml
  auto_prove_sequent.ml
  auto_reverse_sequent.ml
  click_and_collect.eliom
  export_as_coq.ml
  export_as_latex.ml
  is_sequent_provable.ml
  nanoyalla/README.md
  nanoyalla/macroll.v
  notations.ml
  parse_sequent.ml
  proof.ml
  proof_compression.ml
  proof_marshal.ml
  proof_with_notations.ml
  raw_sequent.ml
  rule_request.ml
  sequent.ml
  sequent_with_notations.ml
  static/css/style.css
  static/download/nanoyalla.zip
  static/index.html
  static/js/app.js
  static/js/proof.js
  static/js/sequent.js
  test/api_test.ml
  test/api_test_data.json
  test/proof_test_data/a_a_orth.json
  test/proof_test_data/a_a_orth_bot.json
  test/proof_test_data/a_orth_a.json
  test/proof_test_data/a_par_a^.json
  test/proof_test_data/a_top.json
  test/proof_test_data/axiom_with_notations.json
  test/proof_test_data/delta_delta_with_notations.json
  test/proof_test_data/duals.json
  test/proof_test_data/identity_with_notations.json
  test/proof_test_data/lcm23.json
  test/proof_test_data/list.json
  test/proof_test_data/oc_bot_wn_one.json
  test/proof_test_data/ofcourse_tensor.json
  test/proof_test_data/one_bot.json
  test/proof_test_data/open_a_tensor_one.json
  test/proof_test_data/plus_with.json
  test/proof_test_data/schellinx.json
  test/proof_test_data/selection_with_cut.json
  test/proof_test_data/tensor.json
  test/proof_test_data/tensor_exchange.json
  test/proof_test_data/unfold_cyclic_and_acyclic.json
  test/proof_test_data/wu.json
Labels: feature

#127 Auto-prover with non-recursive notations
  auto_prove_sequent.ml
  proof.ml
  rule_request.ml
  static/index.html
  test/api_test.ml
  test/api_test_data.json
Labels: enhancement

#130 [Coq] rewrite tactic for cyclic notations
  proof.ml
Labels: code improvement

#131 Auto-prover with cyclic notations
  auto_prove_sequent.ml
  focused_proof.ml
  proof.ml
  sequent.ml
  static/index.html
  test/api_test.ml
  test/api_test_data.json
Labels: enhancement

#133 Help notations
  static/css/style.css
  static/index.html
  static/js/app.js
  static/js/proof.js
Labels: documentation

#135 Fix stack overflow
  clauses.ml
  focused_proof.ml
  notations.ml
  proof.ml
  raw_sequent.ml
  sequent.ml
  slice.ml
Labels: bug

#136 [Notations] extend text exports with notations
  export_as_latex.ml
  proof.ml
  raw_sequent.ml
Labels: enhancement

#137 [MAJOR REFACTORING] Switch to opium
  .gitignore
  Makefile
  Makefile.options
  README.md
  click_and_collect.conf.in
  click_and_collect.eliom
  dune
  dune-project
  export_as_latex.ml
  focused_proof.ml
  index.html
  main.ml
  notations.ml
  parse_sequent.ml
  phase.ml
  proof.ml
  proof_compression.ml
  proof_marshal.ml
  raw_sequent.ml
  slice.ml
  static/js/app.js
  static/js/proof.js
  test/api_test.ml
  test/coq_test.sh
  test/latex_test.sh
  test/proof_test_data/litt_with_quote.json
Labels: code improvement

#138 export permutation to latex explicit exchanges
  export_as_latex.ml
  proof.ml
Labels: enhancement

#141 No provability check when acyclic notations. Fixes #139
  export_as_coq.ml
  focused_proof.ml
  is_sequent_provable.ml
  notations.ml
  sequent_with_notations.ml
  test/api_test_data.json
Labels: bug

#142 Axiom expansion
  apply_rule.ml
  index.html
  main.ml
  proof.ml
  proof_compression.ml
  proof_transformation.ml
  proof_with_notations.ml
  request_utils.ml
  sequent_with_notations.ml
  static/css/style.css
  static/js/app.js
  static/js/proof.js
  transform_request.ml
Labels: feature
